name: OVH deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /home/elechatccn
          host: ftp.cluster021.hosting.ovh.net
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}